
#school:
#    enabled: true
#    school-name: 小明学校
#    class-id: 1
#    class-name: 一班
#    student-id: 2
#    student-name: 小明同学
student:
    enabled: true
    students:
        student-id: 1
        student-name: 小明
